spring:
    thymeleaf:
        cache: false # set to false, this if you are working on UI
        prefix: file:main-app/main-webapp/src/main/resources/templates/  #directly serve from src folder instead of target
    web:
        resources:
            static-locations:
                - file:src/main/resources/static/ #directly serve from src folder instead of target
                - classpath:/META-INF/resources/
                - classpath:/resources/
                - classpath:/static/
                - classpath:/public/
#            cache:
#                period: 500000
#            chain:
#                cache: true
    mvc:
        static-path-pattern: /static/**

    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:seedapp}?useUnicode=true&allowPublicKeyRetrieval=true
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:password}
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: none  # we use liquibase
            generate_statistics: true
            naming:
                physical-strategy: gt.app.hibernate.PrefixedNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    jooq:
        sql-dialect: MySQL
    artemis:
        user: ${ACTIVEMQ_ARTEMIS_USER:admin}
        password: ${ACTIVEMQ_ARTEMIS_PASSWORD:admin}
        broker-url: tcp://${ACTIVEMQ_ARTEMIS_HOST:localhost}:${ACTIVEMQ_ARTEMIS_PORT:61616}
    liquibase:
        enabled: true

feign-clients:
    email-service:
        url: http://localhost:8085/ #TODO: use service discovery

logging.level:
    org.jooq.tools.LoggerListener: DEBUG
    org.springframework.security: INFO
    org.springframework.security.web: INFO
    org.springframework.cloud: INFO
#    org.hibernate.SQL: debug
#    org.hibernate.type: TRACE
    'org.hibernate.engine.internal.StatisticalLoggingSessionEventListener': info
