spring:
    application:
        name: Main-APP
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: '@spring.profiles.active@'

    liquibase:
        enabled: false
        change-log: classpath:/liquibase/master.xml
    jpa:
        open-in-view: false
        hibernate:
            naming:
                physical-strategy: gt.app.hibernate.PrefixedNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    cloud:
        openfeign:
            micrometer:
                enabled: true

server:
    port: 8081

logging:
    level:
        security: INFO
        web: INFO
        cloud: INFO
        sql: INFO
        ROOT: WARN
        gt: DEBUG
#        'org.springframework.web.socket': TRACE


app-properties:
    jms:
        content-checkerrequest-queue: jms-content-checker-requestqueue
        content-checkercallback-response-queue: jms-content-checkercallback-responsequeue
    file-storage:
        upload-folder: ${java.io.tmpdir}/uploads

wro4j:
    jmx-enabled: false
    debug: true
    manager-factory:
        post-processors: cssVariables,cssMinJawr,jsMin
        pre-processors: cssUrlRewriting,cssImport,semicolonAppender,removeSourceMaps,singlelineStripper
    filter-url: /wro4j # this is the default, needs to be used in secConfig and the htmls

# https://github.com/gavlyukovskiy/spring-boot-data-source-decorator
decorator:
    datasource:
        enabled: false  # disabled for now
        datasource-proxy:
            slow-query:
                threshold: 1 # 1 second is slow
            query:
                log-level: INFO

management:
    tracing:
        sampling:
            probability: 1.0
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans
    health:
        jms:
            enabled: true
