spring:
    application:
        name: Email Service
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: '@spring.profiles.active@'
    mail:
        host: localhost
        port: ${MAILHOG_PORT:1025}
        username:
        password:

server:
    port: 8085

logging:
    level:
        org.springframework.web: INFO
        ROOT: WARN
        gt: DEBUG

management:
    tracing:
        sampling:
            probability: 1.0
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans


