version: '3'
services:
    activemq_artemis:
        # its not supported in M1 Mac, workaround is to enable Rosetta in Docker
        # Docker settings → Features in development → check ☑ Use Rosetta for x86/amd64 emulation on Apple Silicon, and then restart Docker.
        image: 'apache/activemq-artemis:2.31.2-alpine'
        container_name: activemqArtemis
        environment:
            - ARTEMIS_USER=admin
            - ARTEMIS_PASSWORD=admin
        ports:
            - 8161:8161  # use this to access from browser
            - 61616:61616
        networks:
            - seedappnet
    mysql:
        image: 'mysql:8.0.35'
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=seedapp
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
        networks:
            - seedappnet
    emailhog:
        image: 'richarvey/mailhog'
        container_name: mailhog
        ports:
            - 1025:1025
            - 8025:8025  # use this to access from browser
        networks:
            - seedappnet
    zipkin:
        image: 'openzipkin/zipkin'
        container_name: zipkin
        ports:
            - 9411:9411
        networks:
            - seedappnet
volumes:
    esdata1:
        driver: local
networks:
    seedappnet:
        driver: bridge


#run using
#docker-compose -f docker-compose.yml up
# or just docker-compose up
